### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by device89** [device89/audiocloud#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by ronilbhatia** [comment]
Really great job!! CSS is on point and really matches SoundCloud's. Page is also pretty responsive - very impressive. I do have a few notes:

[ ] Your demo login does not work if I am on the signup modal (it's fine from the sign-in modal). See error I get
![Screen Shot 2019-09-13 at 4 08 10 PM](https://user-images.githubusercontent.com/32026924/64899562-e2a18d00-d640-11e9-9d8f-f92cb87ff263.png)
[ ] Right now the errors are really close to the demo login button - it would be nice if there was a little more space so I would add some top padding to it.
![Screen Shot 2019-09-13 at 4 06 51 PM](https://user-images.githubusercontent.com/32026924/64899578-f947e400-d640-11e9-837f-587aaac6b2c2.png)

**Comment by device89** [comment]
Okay I took care of these issues.
